# Use an official Node.js runtime as the base image
FROM node:20-slim

# Set the working directory inside the container
WORKDIR /app

# Copy only the package.json and lock file first to leverage Docker caching
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the Vite server runs on
EXPOSE 4173

# Command to run the Vite development server
CMD ["npm", "run", "dev"]
