# Use an official Node.js runtime as the base image
FROM node:20-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install project dependencies
RUN npm install --only=production

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the Vite server runs on
EXPOSE 5173

# Command to run the Vite development server
CMD ["npm", "run", "preview"]
